"""empty message

Revision ID: ea998f3059cf
Revises: 791c9681cd3d
Create Date: 2023-12-19 13:39:54.336808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea998f3059cf'
down_revision = '791c9681cd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('occupation')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
